externdef expansionHT:FAR

externdef HufDCLl:BYTE				; HT for DC values of the light intensity (lengths)
externdef HufDCLd:BYTE				; HT for DC values of the light intensity (data)
externdef HufDCCl:BYTE				; HT for DC values of the chrominance (lengths)
externdef HufDCCd:BYTE				; HT for DC values of the chrominance (data)
externdef HufACLl:BYTE				; HT for AC values of the light intensity (lengths)
externdef HufACLd:BYTE				; HT for AC values of the light intensity (data)
externdef HufACCl:BYTE				; HT for AC values of the chrominance (lengths)
externdef HufACCd:BYTE				; HT for AC values of the chrominance (data)

externdef HcodeACL:WORD, HcodeACC:WORD, HcodeDCL:WORD, HcodeDCC:WORD