
; Data
externdef msgData:BYTE

; Methods
externdef PrintNumber:FAR
externdef PrintString:FAR
externdef PrintSpace:FAR
externdef PrintNewLine:FAR
externdef PrintWordSegment:FAR
externdef PrintByteSegment:FAR
externdef WaitForEnter:FAR
externdef initializeWordArray:FAR
externdef initializeByteArray:FAR
externdef intializeWordMatrixDCT:FAR
externdef initializeWordMatrixLarge:FAR
externdef initializeByteMatrix:FAR
externdef initializeWordMatrix:FAR